USE beauty_ecom;

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE OrderItems;
TRUNCATE TABLE Orders;
TRUNCATE TABLE Reviews;
TRUNCATE TABLE Feedback;
TRUNCATE TABLE WholesaleLeads;
TRUNCATE TABLE Users;

SET FOREIGN_KEY_CHECKS = 1;
